.TH SANDSTONE 7 2015-04-28 "Sandstone v3" "Sandstone User's Manual"
.SH NAME
sandstone \- user-space utilities for composable, fine-grained sandboxing in
Linux
.SH DESCRIPTION
.SS Terms
.I Sandboxing
is the virtualisation and confinement of operating-system(OS) resources in
support of executing unreliable code. The
.I art of sandboxing
entails letting the unreliable code make use of OS resources, without letting
it
.I abuse
them to any unintended ends.
